# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :"kernel-update" => {
              :box_name => "kosmonaft/centos7-kernel6.1",
              :box_version => "1",
              :cpus => 2,
              :memory => 1024,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "vmware_desktop" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
    config.vm.provision "shell" do |s|
        s.inline = "uname -r"
      end
    end
  end
end