# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/8"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.define "rpmp" do |rpmp|
    rpmp.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    rpmp.vm.hostname = "rpmp"
    rpmp.vm.provision "shell", path: "rpm_and_repo.sh"
  end
end
